site_name: "AWNET"
site_url: "https://awalford16.github.io"
dev_addr: "127.0.0.1:8080"
repo_url: "https://github.com/awalford16/awalford16.github.io"
theme:
  name: shadcn
  icon: null
  pygments_style:
    light: shadcn-light
    dark: github-dark
  katex_options:
    macros:
      "\\dx": "\\mathrm{d}x"

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  admonition:
  codehilite:
  fenced_code:
  footnotes:
  extra:
  pymdownx.blocks.details:
  pymdownx.tabbed:
  pymdownx.blocks.tab:
    combine_header_slug: true
    separator: ___
  pymdownx.progressbar:
  pymdownx.snippets:
  pymdownx.arithmatex:
    generic: true
  shadcn.extensions.echarts.alpha:
  shadcn.extensions.codexec:
  shadcn.extensions.iconify:
  pymdownx.blocks.caption:
